### PR TITLE
Use the same TESTNET_NAME as in CosmWasm/testnets

### PR DESCRIPTION
**Pull request by webmaster128**
See https://github.com/CosmWasm/testnets/blob/master/coral/defaults.env#L2

### CODE REVIEW

**Review by orkunkl — COMMENTED** [review]
So the way I used `$TESTNET_NAME` is to `cd` users to testnet directory. As seen in docs:
```bash
cd $CW_DIR
## Fork github.com:CosmWasm/testnets to your account and clone.
## You cannot push directly to CosmWasm/testnets repo
git clone git@github.com:<your-name>/testnets
cd testnets
git checkout -b add-gen-acc-<validator-name>
cd $TESTNET_NAME
```
to apply this change we need to change `testnets/coral` directory to `testnets/coralnet`. Or add one more `$TESTNET_DIR` env variable

**Comment by orkunkl** [comment]
If we insist on naming `coral` to `coralnet`. I will change all the references

**Comment by webmaster128** [comment]
Ah, I see. We can also change it in CosmWasm/testnets.

The cleanest way would be to rename the folder because we agreed on the following names:
- Coralnet (chain ID "cosmwasm-coral")
- Gaia Flex (chain ID "gaia-flex")

**Comment by orkunkl** [comment]
Alright! Closing the PR now. I will create one

**Comment by webmaster128** [comment]
Thank you @orkunkl!

**Pull request closed without merging**
