### PR TITLE
fix: title in sidebar

### PR DESCRIPTION
**Pull request by tac0turtle**
cw3-flex-multisig was shown as cw3-fixed-multisig in sidebar

### CODE REVIEW

**Review by ethanfrey — APPROVED** [review]
Thanks

**Comment by ethanfrey** [comment]
@orkunkl does this auto-deploy on merge or do you need to manually update the docs site?

**Comment by tac0turtle** [comment]
> @orkunkl does this auto-deploy on merge or do you need to manually update the docs site?

It auto deploys (https://github.com/CosmWasm/docs/blob/master/.github/workflows/main.yml#L31)

**Comment by orkunkl** [comment]
Thank you so much.

**Pull request merged**
